In [1]:
import numpy as np

In [3]:
np.array([1,2])

array([1, 2])

In [5]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
np.ones_like(np.zeros(10))

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [23]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [25]:
np.arange(1,10).reshape(2,5)

ValueError: cannot reshape array of size 9 into shape (2,5)

In [29]:
np.arange(25).reshape(5,5)[0]

array([0, 1, 2, 3, 4])

In [31]:
2 + np.array([1,2,3,4])

array([3, 4, 5, 6])

In [33]:
np.arange(1,10).sum()

45